#!/bin/bash
set -xeuo pipefail

. ${KOLA_EXT_DATA}/libtest.sh

tmpdir=$(mktemp -d)
cd "${tmpdir}"
echo "using tmpdir: ${tmpdir}"
touch .testtmp
trap cleanup EXIT
function cleanup () {
  if test -z "${TEST_SKIP_CLEANUP:-}"; then
    if test -f "${tmpdir}"/.testtmp; then
      cd /
      rm "${tmpdir}" -rf
    fi
  else
    echo "Skipping cleanup of ${tmpdir}"
  fi
}

# Mount the EFI partition.
tmpefimount=$(mount_tmp_efi)
# Path to <tmp_efi_mount>/EFI
tmpefidir=${tmpefimount}/EFI
# /usr/lib/bootupd/updates
bootupdir=/usr/lib/bootupd/updates
# fedora
efisubdir=fedora
# /usr/lib/bootupd/updates/EFI
efiupdir=${bootupdir}/EFI
# /usr/lib/ostree-boot/efi/EFI
ostbaseefi=/usr/lib/ostree-boot/efi/EFI
# /usr/lib/ostree-boot/efi/EFI/fedora
ostefi=${ostbaseefi}/${efisubdir}
shimx64=shimx64.efi
grubx64=grubx64.efi
usrlibefi=/usr/lib/efi
# Path to <tmp_efi_mount>/EFI/fedora
tmpefisubdir=${tmpefidir}/${efisubdir}

if [ -d efilib ]; then efilib_exists=true; else efilib_exists=false; fi

prepare_efi_update() {
  test -w /usr
  rm -rf ${bootupdir}/EFI.json
}

prepare_efi_update_old_layout() {
  test -w /usr
  mkdir -p ${ostbaseefi}
  cp -a ${efiupdir}.orig/* ${ostbaseefi}/
  rm -rf ${efiupdir} ${bootupdir}/EFI.json
}

# backup: update_metadata_move EFI EFI-bak
# restore: update_metadata_move EFI-bak EFI
update_metadata_move() {
  local src="${bootupdir}/$1.json"
  local dst="${bootupdir}/$2.json"

  [ -w "$bootupdir" ]
  [ -f "$src" ]
  [ ! -e "$dst" ]

  mv -- "$src" "$dst"
}

if $efilib_exists; then
    # Find the files under usr/lib/efi after transferred
    shim_path=$(find ${usrlibefi} -name shim.efi)
    shimx64_path=$(find ${usrlibefi} -name ${shimx64})
    grubx64_path=$(find ${usrlibefi} -name ${grubx64})

    test -n "${shimx64_path}" && test -n "${grubx64_path}"
    test -d "/usr/lib/bootupd/updates/EFI" && exit 1
else
    shim_path=$(find ${bootupdir} -name shim.efi)
    shimx64_path=$(find ${bootupdir} -name ${shimx64})
    grubx64_path=$(find ${bootupdir} -name ${grubx64})

    test -n "${shimx64_path}" && test -n "${grubx64_path}"
fi

bootupctl status > out.txt
evr=$(rpm -q grub2-common --qf '%{EVR}')
assert_file_has_content_literal out.txt 'Component EFI'
if  $efilib_exists; then
    assert_file_has_content_literal out.txt '  Installed: grub2-'"${evr}"
else
    assert_file_has_content_literal out.txt '  Installed: grub2-efi-x64-'
fi
assert_file_has_content_literal out.txt 'Update: At latest version'
assert_file_has_content out.txt '^CoreOS aleph version:'
ok status

bootupctl validate | tee out.txt
ok validate

if env LANG=C.UTF-8 runuser -u bin bootupctl status 2>err.txt; then
  fatal "Was able to bootupctl status as non-root"
fi
assert_file_has_content err.txt 'error: This command requires root privileges'

# From here we'll fake updates
test -w /usr || rpm-ostree usroverlay

if $efilib_exists; then
    prepare_efi_update
    rm -v "${shim_path}"
    echo bootupd-test-changes >> "${grubx64_path}"
else
    # Save a backup copy of the update dir
    cp -a ${efiupdir} ${efiupdir}.orig
    prepare_efi_update_old_layout
    rm -v ${ostefi}/shim.efi
    echo bootupd-test-changes >> ${ostefi}/grubx64.efi
fi

/usr/libexec/bootupd generate-update-metadata /
ver=$(jq -r .version < ${bootupdir}/EFI.json)
vers=$(jq -r .versions < ${bootupdir}/EFI.json)
test='[{"name": "test", "rpm_evr": ""}]'
new=$(echo "$vers" "$test" | jq -s add)
cat >ver.json << EOF
{ "version": "${ver},test", "versions": ${new}, "timestamp": "$(date -u --iso-8601=seconds)" }
EOF
jq -s add ${bootupdir}/EFI.json ver.json > new.json
mv new.json ${bootupdir}/EFI.json

bootupctl status | tee out.txt
assert_file_has_content_literal out.txt 'Component EFI'
if  $efilib_exists; then
    assert_file_has_content_literal out.txt '  Installed: grub2-'"${evr}"
else
    assert_file_has_content_literal out.txt '  Installed: grub2-efi-x64-'
fi
assert_not_file_has_content out.txt '  Installed: grub2-.*,test'
assert_file_has_content_literal out.txt 'Update: Available:'
ok update avail

bootupctl status --json > status.json
jq -r '.components.EFI.installed.version' < status.json > installed.txt

if  $efilib_exists; then
    assert_file_has_content installed.txt '^grub2-'"${evr}"
else
    assert_file_has_content installed.txt '^grub2-efi-x64'
fi

bootupctl update | tee out.txt
assert_file_has_content out.txt 'Updated EFI: grub2-.*,test'

bootupctl status > out.txt
assert_file_has_content_literal out.txt 'Component EFI'
assert_file_has_content out.txt '  Installed: grub2-.*,test'
assert_file_has_content_literal out.txt 'Update: At latest version'
ok status after update

bootupctl validate | tee out.txt
ok validate after update

# FIXME see above
# assert_file_has_content ${tmpefidir}/${efisubdir}/somenew.efi 'somenewfile'
if test -f "${tmpefisubdir}/shim.efi"; then 
  fatal "failed to remove file"
fi
if ! grep -q 'bootupd-test-changes' "${tmpefisubdir}/${grubx64}"; then
  fatal "failed to update modified file"
fi
cmp "${tmpefisubdir}/${shimx64}" "${shimx64_path}"
ok filesystem changes

bootupctl update | tee out.txt
assert_file_has_content_literal out.txt 'No update available for any component'
assert_not_file_has_content_literal out.txt 'Updated EFI'

mount -o remount,rw /boot
rm -f /boot/bootupd-state.json

if [ -d /sys/firmware/efi ]; then
  # EFI boot: verify update failed if metadata is missing EFI.json
  # Backup EFI.json and restore it later, or validate will fail
  update_metadata_move EFI EFI-bak
  if bootupctl update 2>err.txt; then
    fatal "Should fail as missing EFI update metadata (booted with EFI)"
  fi
  update_metadata_move EFI-bak EFI

  # Should succeed if BIOS metadata is missing
  bootupctl remove-component bios
  bootupctl update | tee out.txt
  assert_file_has_content out.txt 'Adopted and updated: EFI:'
  assert_not_file_has_content out.txt 'Adopted and updated: BIOS:'

else
  # BIOS boot: verify update failed if metadata is missing BIOS.json
  # Backup BIOS.json and restore it later, or validate will fail
  update_metadata_move BIOS BIOS-bak
  if bootupctl update 2>err.txt; then
    fatal "Should fail as missing BIOS update metadata (booted with BIOS)"
  fi
  update_metadata_move BIOS-bak BIOS

  # Should succeed if EFI metadata is missing
  bootupctl remove-component efi
  bootupctl update | tee out.txt
  assert_file_has_content out.txt 'Adopted and updated: BIOS:'
  assert_not_file_has_content out.txt 'Adopted and updated: EFI:'
fi

echo "some additions" >> "${tmpefisubdir}/${shimx64}"
if bootupctl validate 2>err.txt; then
  fatal "unexpectedly passed validation"
fi
assert_file_has_content err.txt "Changed: .*${efisubdir}/${shimx64}"
test "$(grep -cEe '^Changed:' err.txt)" = "1"
ok validate detected changes

tap_finish
