[package]
name = "bootupd"
description = "Bootloader updater"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2018"

[[bin]]
name = "bootupd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "~2.33"
env_logger = "^0.7"
fs2 = "0.4.3"
hex = "0.4.2"
libc = "^0.2"
libsystemd = "^0.2"
log = "^0.4"
nix = "0.19.0"
openat = "0.1.19"
openat-ext = "^0.1.6"
openssl = "^0.10"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
structopt = "0.3"
tempfile = "^3.1"

[profile.release]
# We assume we're being delivered via e.g. RPM which supports split debuginfo
debug = true
