[package]
name = "bootupd"
description = "Bootloader updater"
license = "Apache-2.0"
version = "0.2.7-alpha.0"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2018"

[[bin]]
name = "bootupd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bincode = "1.3.2"
chrono = { version = "0.4.11", features = ["serde"] }
clap = ">= 2.33, < 3.1"
env_logger = ">= 0.8, < 0.10"
fn-error-context = "0.2.0"
fs2 = "0.4.3"
hex = "0.4.3"
lazy_static = "1.4.0"
libc = "^0.2"
libsystemd = ">= 0.3, < 0.5"
log = "^0.4"
nix = ">= 0.22.1, < 0.24.0"
openat = "0.1.20"
openat-ext = "^0.2.2"
openssl = "^0.10"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
structopt = "0.3"
tempfile = "^3.3"

[profile.release]
# We assume we're being delivered via e.g. RPM which supports split debuginfo
debug = true

[package.metadata.release]
disable-publish = true
disable-push = true
post-release-commit-message = "cargo: development version bump"
pre-release-commit-message = "cargo: bootupd release {{version}}"
sign-commit = true
sign-tag = true
tag-message = "bootupd {{version}}"
