[package]
name = "bootupd"
description = "Bootloader updater"
license = "Apache-2.0"
version = "0.2.8"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2021"
rust-version = "1.58.1"

# See https://github.com/cgwalters/cargo-vendor-filterer
[package.metadata.vendor-filter]
platforms = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[[bin]]
name = "bootupd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bincode = "1.3.2"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "3.2", default-features = false, features = ["cargo", "derive", "std", "suggestions"] }
env_logger = ">= 0.8, < 0.10"
fn-error-context = "0.2.0"
fs2 = "0.4.3"
hex = "0.4.3"
libc = "^0.2"
libsystemd = ">= 0.3, < 0.6"
log = "^0.4"
nix = ">= 0.22.1, < 0.27.0"
openat = "0.1.20"
openat-ext = ">= 0.2.2, < 0.3.0"
openssl = "^0.10"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tempfile = "^3.3"

[profile.release]
# We assume we're being delivered via e.g. RPM which supports split debuginfo
debug = true

[package.metadata.release]
disable-publish = true
disable-push = true
post-release-commit-message = "cargo: development version bump"
pre-release-commit-message = "cargo: bootupd release {{version}}"
sign-commit = true
sign-tag = true
tag-message = "bootupd {{version}}"
