name: Cross build

on: [push, pull_request]

permissions:
  actions: read

jobs:
  crossarch-check:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu_latest
          - arch: ppc64le
            distro: ubuntu_latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          set-safe-directory: true

      - uses: uraimo/run-on-arch-action@v3.0.1
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          run: |
            set -xeu
            apt update -y
            apt install -y gcc make curl libssl-dev pkg-config
            # Install Rust 1.84.1
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.84.1
            source $HOME/.cargo/env
            rustc --version
            cargo check
